//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.12.10 at 08:48:00 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/generateSchema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.gmit.sw.rmi;
